# Generated by Django 3.1.7 on 2021-04-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=60)),
                ('lastname1', models.CharField(max_length=30)),
                ('lastname2', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('sex', models.IntegerField()),
            ],
        ),
    ]
